services:
  server:
    build: .
    ports:
      - "8099:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/swansea.db
      - METADATA_PATH=/metadata
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./metadata:/metadata
    restart: unless-stopped
